name: Publish binaries to Github

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Install dependencies
      run: go mod tidy

    - name: Build binaries for nitro and bridge
      run: |
        go build -v -o nitro .
        go build -o nitro-bridge cmd/start-bridge/main.go

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nitro-and-bridge-binaries
        path: |
          nitro
          nitro-bridge

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: nitro-and-bridge-binaries

    - name: Upload nitro binary to GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          nitro
          nitro-bridge
        name: |
          nitro
          bridge

    # - name: Create release in git.vdb.to/cerc-io/nitro
    #   id: create_release
    #   run: |
    #     NAME=$(echo '${{ toJson(github.event.release) }}' | jq -r '.name')
    #     TAG_NAME=$(echo '${{ toJson(github.event.release) }}' | jq -r '.tag_name')

    #     RELEASE_RESPONSE=$(curl -s -X POST "https://git.vdb.to/api/v1/repos/cerc-io/nitro/releases" \
    #       -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
    #       -H "Content-Type: application/json" \
    #       -d '{
    #         "tag_name": "'"$TAG_NAME"'",
    #         "target_commitish": "main",
    #         "name": "'"$NAME"'",
    #         "body": "Created by GitHub CI",
    #         "draft": false,
    #         "prerelease": false
    #       }')
    #     echo "::set-output name=release_id::$(echo $RELEASE_RESPONSE | jq -r '.id')"

    # - name: Upload nitro binary to git.vdb release
    #   run: |
    #     curl -X POST "https://git.vdb.to/api/v1/repos/cerc-io/nitro/releases/${{ steps.create_release.outputs.release_id }}/assets?name=nitro" \
    #     -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
    #     -H "Content-Type: multipart/form-data" \
    #     --form "attachment=@nitro"

    # - name: Upload bridge binary to git.vdb release
    #   run: |
    #     curl -X POST "https://git.vdb.to/api/v1/repos/cerc-io/nitro/releases/${{ steps.create_release.outputs.release_id }}/assets?name=bridge" \
    #     -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
    #     -H "Content-Type: multipart/form-data" \
    #     --form "attachment=@nitro-bridge"
